chore: migrate default branch from master to main
googleapis/python-language pull request #182
Opened 2021-08-27 17:53 UTC by leahecole

2021-08-27 18:53 UTC, dandhlee requested changes

2021-08-27 19:14 UTC, dandhlee reviewed
One more, almost there!

2021-08-31 21:57 UTC, parthea commented
Hi @leahecole, Please could you take a look?

2021-09-01 11:25 UTC, parthea commented on README.rst
> +   :target: https://github.com/googleapis/google-cloud-python/blob/main/README.rst#general-availability
Done.

2021-09-01 11:26 UTC, parthea commented
@googlebot I consent.

2021-09-01 11:27 UTC, parthea approved these changes

2021-09-01 11:27 UTC, parthea commented
Hi @dandhlee, Please can you take another look?

2021-09-01 20:24 UTC, closed without merging