chore: delete owlbot.py
googleapis/python-language pull request #213
Opened 2021-10-27 11:01 UTC by parthea

Now that googleapis/synthtool#1244 is merged, owlbot.py is no longer required in this repo. We can add owlbot.py back in the future if repository specific customizations are needed.

2021-10-27 20:27 UTC, busunkim96 requested changes
There seem to be some unpublished files that result in a sphinx error:

```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 328, in build
    self.env.check_consistency()
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 627, in check_consistency
    logger.warning(__('document isn\'t included in any toctree'),
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1812, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 123, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1844, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1512, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    rv = self.filter(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 811, in filter
    result = f.filter(record)
  File "/tmpfs/src/github/python-language/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: /tmpfs/src/github/python-language/docs/api.rst:document isn't included in any toctree
```

2021-11-04 16:21 UTC, parthea commented
`docs/api.rst` looks to be redundant now that we have `docs/index.rst` which is autogenerated. `docs/usage.rst` hasn't been updated since 2018. I'd like to remove in favor of `samples/snippets` which is consistent across all googleapis/python-* repos.

2021-11-09 17:24 UTC, busunkim96 approved these changes

2021-11-09 17:24 UTC, busunkim96 commented
Ah sorry, I don't think this made it through my normal filter. Could you please "re-request" a review if I've looked at a PR previously? Thanks!

2021-11-09 18:05 UTC, merged